FROM registry.cn-hongkong.aliyuncs.com/oj-image/backend:1.6.1

# 后端 Python 源码
COPY ./OnlineJudge/account /app/account
COPY ./OnlineJudge/announcement /app/announcement
COPY ./OnlineJudge/conf /app/conf
COPY ./OnlineJudge/contest /app/contest
COPY ./OnlineJudge/fps /app/fps
COPY ./OnlineJudge/judge /app/judge
COPY ./OnlineJudge/oj /app/oj
COPY ./OnlineJudge/options /app/options
COPY ./OnlineJudge/problem /app/problem
COPY ./OnlineJudge/submission /app/submission
COPY ./OnlineJudge/utils /app/utils
COPY ./OnlineJudge/manage.py /app/manage.py

# 定制前端构建产物（覆盖镜像内置的官方前端）
COPY ./OnlineJudgeFE/dist /app/dist
